apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: mar11-ragupdatedimage-2-database
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mar11-ragupdatedimage-2-database
    app.kubernetes.io/part-of: mar11-ragupdatedimage-2
  name: mar11-ragupdatedimage-2-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: mar11-ragupdatedimage-2-database
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: mar11-ragupdatedimage-2-database
    spec:
      containers:
        - image: quay.io/rh-ee-jdubrick/chroma:test
          name: database
          args: ["--workers", "1", "--host", "0.0.0.0", "--port", "8000", "--proxy-headers", "--log-config", "chromadb/log_config.yml", "--timeout-keep-alive", "30"]
          ports:
            - containerPort: 8000
          securityContext:
            runAsNonRoot: true
